name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - set-user
          - system-pkgs
          - homebrew
        baseImage:
          - ubuntu:18.04
          - ubuntu:20.04
          - ubuntu:22.04
          - debian:oldstable-slim
          - debian:stable-slim
          - debian:unstable-slim
        include:
          - features: "set-user"
            baseImage: "alpine:latest"
          - features: "system-pkgs"
            baseImage: "alpine:latest"
          - features: "python-pkgs"
            baseImage: "python:3-slim"
    steps:
      - uses: actions/checkout@main

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@main

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
