name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - set-user
          - system-pkgs
          - python-pkgs
        baseImage:
          - ubuntu:latest
          - debian:stable
          - debian:stable-slim
          - python:3-slim
        include:
          - features: "set-user"
            baseImage: "alpine:latest"
          - features: "system-pkgs"
            baseImage: "alpine:latest"
          - features: "python-pkgs"
            baseImage: "python:3.6-slim"
          - features: "python-pkgs"
            baseImage: "python:3.7-slim"
          - features: "python-pkgs"
            baseImage: "python:3.8-slim"
          - features: "python-pkgs"
            baseImage: "python:3.9-slim"
          - features: "python-pkgs"
            baseImage: "python:3.10-slim"
          - features: "python-pkgs"
            baseImage: "python:3.11-slim"
    steps:
      - uses: actions/checkout@main

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@main

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
