name: "CI - Test Features"
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - test/**
  pull_request:
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@main
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            set-user: ./**/set-user/**
            system-pkgs: ./**/system-pkgs/**
            python-pkgs: ./**/python-pkgs/**
            homebrew: ./**/homebrew/**
            chezmoi: ./**/chezmoi/**

  test:
    needs: detect-changes
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        features: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
        baseImage:
          - ubuntu:18.04
          - ubuntu:20.04
          - ubuntu:22.04
          - debian:oldstable-slim
          - debian:stable-slim
          - debian:unstable-slim
    steps:
      - uses: actions/checkout@main

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@main

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
